[package]
name = "testing-binary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
num = "0.4.0"
serde = { version = "1.0.139", optional = true }